# Generated by Django 5.1.2 on 2024-11-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="monitor",
            table="myapp_monitor",
        ),
    ]
