# Generated by Django 5.1.2 on 2024-11-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_monitor_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="monitor",
            table="monitor",
        ),
    ]
