# Generated by Django 5.1.3 on 2024-11-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_monitor_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
